---
title: "C6320 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6320"
helpviewer_keywords: 
  - "C6320"
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 10
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 10
---
# C6320
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Avertissement C6320 : l'expression de filtre d'exception correspond à la constante EXCEPTION\_EXECUTE\_HANDLER.  Cela risque de masquer les exceptions qui n'étaient pas destinées à être gérées  
  
 Cet avertissement indique l'effet secondaire lié à l'utilisation de la constante EXCEPTION\_EXECUTE\_HANDLER dans le bloc \_\_except.  Dans ce cas, l'instruction dans le bloc \_\_except s'exécute toujours pour gérer l'exception, y compris les exceptions vous ne souhaitiez pas gérer dans une fonction particulière.  Il est recommandé de vérifier l'exception avant de la gérer.  
  
## Exemple  
 Le code suivant génère cet avertissement car le bloc \_\_except tente de gérer les exceptions de tous les types :  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Pour corriger cet avertissement, utilisez `GetExceptionCode` pour vérifier une exception particulière avant de la gérer, comme indiqué dans le code suivant :  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## Voir aussi  
 [try\-except, instruction](/visual-cpp/cpp/try-except-statement)